import React, { PureComponent } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Modal, Button } from 'antd';

import styles from '../styles/Home.module.css'


class Home extends PureComponent {
  constructor(props) {
    super(props)
    this.ref = React.createRef();
    this.state = {
    }
  }
  componentDidMount() {
    let Fthis = this
    this.setState({
      ready: true,
    })
  }
  render() {
    let Fthis = this
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            2sWelcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>
          <Button type="primary">Primary Button</Button>



          <Modal
            title={null}
            visible={true}
          // onOk={handleOk}
          //  onCancel={handleCancel}
          >
            <p>Some contents...</p>
            <p>Some contents...</p>
            <p>Some contents...</p>
          </Modal>

        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}


export default Home